spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cashnamu_v2_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: cashnamu
    password: cashnamu0!
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace   
    
